### PR TITLE
"Fix" M2 Mac `TDFieldExporter2D` problem.

### LINKED ISSUE #129: Memory leak in `TDFieldExporter2D::export_field`
Not sure why yet, but we have a segmentation violation (I think from the 2D field exporter)...
```
➤ tdms in_pstd_cyl.mat output.mat
[2022-10-10 16:47:51.417] [debug] Parsing 3 command line arguments
infile:[in_pstd_cyl.mat], outfile:[output.mat], m=0
[2022-10-10 16:47:51.417] [debug] Finished parsing arguments
[2022-10-10 16:47:51.425] [info] Using 8 OMP threads
[2022-10-10 16:47:51.425] [info] Isource is empty
[2022-10-10 16:47:51.425] [info] Jsource is empty
[2022-10-10 16:47:51.425] [debug] f_ex_vec has ndims=2 N=1
[2022-10-10 16:47:51.425] [info] interpolation method = 1
[2022-10-10 16:47:51.425] [info] exi not present
[2022-10-10 16:47:51.425] [info] eyi not present
[2022-10-10 16:47:51.425] [info] Ni_tdf=276 Nk_tdf=276
[2022-10-10 16:47:51.425] [info] Refractive index = 1.35001
[2022-10-10 16:47:52.470] [debug] init_diff_shift_op, delta=-0.5
[2022-10-10 16:47:52.470] [debug] init_diff_shift_op, delta=-0.5
[2022-10-10 16:47:52.470] [debug] init_diff_shift_op, delta=-0.5
[2022-10-10 16:47:52.470] [debug] init_diff_shift_op, delta=0.5
[2022-10-10 16:47:52.470] [debug] init_diff_shift_op, delta=0.5
[2022-10-10 16:47:52.470] [debug] init_diff_shift_op, delta=0.5
[2022-10-10 16:47:52.470] [info] Np=2 Nt=500 Npe=250 f_max=2.94577e+14 Npraw=0.4606
dims:(254,1,254)
[2022-10-10 16:47:52.476] [debug] Starting main loop
[2022-10-10 16:47:52.488] [info] Saving field
[2022-10-10 16:47:52.488] [debug] Entered TDFieldExporter2D::export_field
[2022-10-10 16:47:52.488] [debug] Entered field written to array, creating output filename
[2022-10-10 16:47:52.488] [debug] output folder name: ??
[2022-10-10 16:47:52.488] [debug] output file name: ??/ex_000000.mat
time domain output: ??/ex_000000.mat
[2022-10-10 16:47:52.488] [debug] About to write matlab_array to the MATLAB output file
zsh: segmentation fault  tdms in_pstd_cyl.mat output.mat
```

Seems to only appear once debug logging was turned on. Which is rather alarming.

### LINKED ISSUE #255: Garbage when reading in a blank string for `tdfdir` on M2 Mac.
Possibly related to #191.
Probably related to #211.
Superficially fixed by PR #254.

# Bug investigation:

I noticed on (and only on?) my M2 Mac that all of the system tests fail. Unzipping the contents of `arc_01.zip` and running interactively (with a lot of debug printout), I get:
```bash
./tdms pstd_fs_input.mat fs_output.mat
[2023-03-10 11:31:59.189] [debug] Parsing 3 command line arguments
[2023-03-10 11:31:59.189] [info] Output file specified: fs_output.mat
[2023-03-10 11:31:59.189] [debug] Finished parsing arguments
[2023-03-10 11:31:59.190] [info] Input file: pstd_fs_input.mat | No gridfile supplied
[2023-03-10 11:31:59.196] [info] exi not present
[2023-03-10 11:31:59.196] [info] eyi not present
[2023-03-10 11:31:59.196] [info] Using pseudospectral method (PSTD)
[2023-03-10 11:31:59.196] [info] Using band-limited interpolation where possible
[2023-03-10 11:31:59.196] [debug] Finding the string: 'sourcemode'
[2023-03-10 11:31:59.196] [debug] This string is 7 chars long.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'sourcemode' = 'pulsed'.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'sourcemode' = 'pulsed'.
[2023-03-10 11:31:59.196] [debug] Finding the string: 'runmode'
[2023-03-10 11:31:59.196] [debug] This string is 9 chars long.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'runmode' = 'complete'.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'runmode' = 'complete'.
[2023-03-10 11:31:59.196] [debug] Finding the string: 'dimension'
[2023-03-10 11:31:59.196] [debug] This string is 2 chars long.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'dimension' = '3'.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'dimension' = '3'.
[2023-03-10 11:31:59.196] [info] intmethod = 1
[2023-03-10 11:31:59.196] [info] exi not present
[2023-03-10 11:31:59.196] [info] eyi not present
[2023-03-10 11:31:59.196] [info] f_ex_vec has ndims=2 N=512
[2023-03-10 11:31:59.196] [info] Np = 2, Nt = 500, Npe = 250, f_max = 2.94577e+14, Npraw = 0.4606
[2023-03-10 11:31:59.196] [debug] Finding the string: 'tdfdir'
[2023-03-10 11:31:59.196] [debug] This string is 1 chars long.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'tdfdir' = ''.
[2023-03-10 11:31:59.196] [debug] Have got the string. 'tdfdir' = ''.
[2023-03-10 11:31:59.196] [debug] Will write the TD fields to '?'
[2023-03-10 11:31:59.196] [info] Ni_tdf = 276, Nk_tdf = 276
[2023-03-10 11:31:59.196] [debug] Will write the TD fields to '?'
[2023-03-10 11:31:59.196] [info] Isource is empty
[2023-03-10 11:31:59.196] [info] Jsource is empty
[2023-03-10 11:31:59.196] [info] f_ex_vec has ndims=2 N=512
[2023-03-10 11:31:59.197] [debug] init_diff_shift_op, delta=-0.5
[2023-03-10 11:31:59.197] [debug] init_diff_shift_op, delta=-0.5
[2023-03-10 11:31:59.197] [debug] init_diff_shift_op, delta=-0.5
[2023-03-10 11:31:59.197] [debug] init_diff_shift_op, delta=0.5
[2023-03-10 11:31:59.197] [debug] init_diff_shift_op, delta=0.5
[2023-03-10 11:31:59.197] [debug] init_diff_shift_op, delta=0.5
[2023-03-10 11:32:00.245] [info] dims: (254,1,254)
[2023-03-10 11:32:00.251] [info] Using 8 OMP threads
[2023-03-10 11:32:00.251] [info] refind (Refractive index) = 1.350014e+00
[2023-03-10 11:32:00.251] [info] Starting main looop
[2023-03-10 11:32:00.266] [info] Exporting field... folder_name = 
[2023-03-10 11:32:00.266] [debug] folder_name = 
[2023-03-10 11:32:00.266] [debug] folder_name = 
time domain output: /ex_000000.mat
[2023-03-10 11:32:00.266] [debug] Opened file /ex_000000.mat
0x117844b20
zsh: segmentation fault  ./tdms pstd_fs_input.mat fs_output.mat
```

### Investigation:
* The 'tifdir' is an empty string (this is verified in the input .mat file).
* The `matlabio.cpp::string_in` function correctly reads in an empty `char *` this is propagated to the `IndependentObjectsFromInfile` constructor.
* But! Gets replaced by garbage (i.e. is not empty) during a conversion between `std::string` and `char*`. And since the design is that a non-empty 'tdfdir' means "write out the field", tdms tries to write out a field to the root of my file system (`/`).

### PR DESCRIPTION
**Pull request by samcunliffe**
3b0fcb3d6cbdf92425d46012bdfde3f6114d6dd7 fixes the problem with exporting the fields to a non-existent directory. And since I've got the context in my head, I replaced `char* folder_name` in the `TDFieldExporter2D` to an `std::string` and did some sanity refactoring in 9fbe3e70fd8c596c9584d7f0d4cc18d52f04567f.

Probably related to #211. Superficially fixes #255 (I retrospectively created a bug report) and fixes #129 (I forgot that we'd seen this before and it disappeared).

### CODE REVIEW

File: tdms/src/fields/td_field_exporter_2d.cpp [hunk 1]
```diff
@@ -1,8 +1,10 @@
 #include "field.h"
 
 #include <stdexcept>
+#include <string>
```
Comment (willGraham01) [inline tdms/src/fields/td_field_exporter_2d.cpp:4]:
```suggestion
#include <string>

#include <spdlog/spdlog.h>
```
Explicit include of SPDLOG (it's not included in `field.h`)?

**Review by willGraham01 — APPROVED** [review]
